services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5123:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  pgdata:
